### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by llcc** [xuchunyang/youdao-dictionary.el#1]
Dear,

I can only search one time after launching emacs every time. When I search the second time, a error message appeared as:

Contacting host: fanyi.youdao.com:80 byte-code: Invalid date: 13-Jan-2045 01:03:12.00 GMT 

What will the problem probably be?
Thanks.

**Comment by xuchunyang** [comment]
> Contacting host: fanyi.youdao.com:80 byte-code: Invalid date: 13-Jan-2045 01:03:12.00 GMT

2045? It's obviously impossible. Do you have a correct time setup in your Emacs? you check this by run `(current-time-string)` in Emacs?

**Comment by llcc** [comment]
Maybe it is a youdao serve request related problem in my opinion.
The time in my emacs is correct.

**Comment by xuchunyang** [comment]
I don't have this issue. 

Can you click http://fanyi.youdao.com/openapi.do?keyfrom=YouDaoCV&key=659600698&type=data&doctype=json&version=1.1&q=example
and run the following in your Emacs?
```lisp
(url-retrieve-synchronously "http://fanyi.youdao.com/openapi.do?keyfrom=YouDaoCV&key=659600698&type=data&doctype=json&version=1.1&q=example")
```
both above should works fine.

**Comment by llcc** [comment]
That's very weird.

I can get the json from your link in websites. However, I can only pass once by using =(url-retrieve-synchronously link)=, never lucky for second time. Here is the full error message:
```
Debugger entered--Lisp error: (error "Invalid date: 13-Jan-2045 07:27:27.00 GMT")
  signal(error ("Invalid date: 13-Jan-2045 07:27:27.00 GMT"))
  error("Invalid date: %s" "13-Jan-2045 07:27:27.00 GMT")
  byte-code("\300\301\302\217\207" [nil (byte-code "\301\302\303\304!!\"\207" [date apply encode-time parse-time-string timezone-make-date-arpa-standard] 5) ((error (error "Invalid date: %s" date)))] 3)
  date-to-time("13-Jan-2045 07:27:27.00 GMT")
  url-cookie-expired-p([url-cookie "OUTFOX_SEARCH_USER_ID" "534665729@118.103.54.78" "13-Jan-2045 07:27:27.00 GMT" "/" "youdao.com" nil])
  url-cookie-retrieve("fanyi.youdao.com" "/openapi.do?keyfrom=YouDaoCV&key=659600698&type=data&doctype=json&version=1.1&q=example" nil)
  url-cookie-generate-header-lines("fanyi.youdao.com" "/openapi.do?keyfrom=YouDaoCV&key=659600698&type=data&doctype=json&version=1.1&q=example" nil)
  url-http-create-request()
  url-http([cl-struct-url "http" nil nil "fanyi.youdao.com" nil "/openapi.do?keyfrom=YouDaoCV&key=659600698&type=data&doctype=json&version=1.1&q=example" nil nil t nil t] #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] (nil))
  url-retrieve-internal("http://fanyi.youdao.com/openapi.do?keyfrom=YouDaoCV&key=659600698&type=data&doctype=json&version=1.1&q=example" #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] (nil) nil nil)
  url-retrieve("http://fanyi.youdao.com/openapi.do?keyfrom=YouDaoCV&key=659600698&type=data&doctype=json&version=1.1&q=example" #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] nil nil nil)
  url-retrieve-synchronously("http://fanyi.youdao.com/openapi.do?keyfrom=YouDaoCV&key=659600698&type=data&doctype=json&version=1.1&q=example")
  eval((url-retrieve-synchronously "http://fanyi.youdao.com/openapi.do?keyfrom=YouDaoCV&key=659600698&type=data&doctype=json&version=1.1&q=example") nil)
  eval-last-sexp-1(nil)
  eval-last-sexp(nil)
  #<subr call-interactively>(eval-last-sexp nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> eval-last-sexp nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (eval-last-sexp nil nil))
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

**Comment by xuchunyang** [comment]
In `(url-retrieve-synchronously link)`, does any other link work fine? I guess `url-retrieve-synchronously` may use a wrong date hence all url requests will not work.

**Comment by llcc** [comment]
Totally no idea what happened.
I tried some URLs, they all worked properly.
It seems that it is a specific problem of youdao request.

**Comment by llcc** [comment]
Hi @xuchunyang,

Finally i solved the problem by the code of link: https://github.com/punchagan/org2blog/issues/176.

And a feature request:
The sentence example of looking-up word is very useful in some situations. I am not sure if youdao API opens it or not, but if yes, can you implement it?

Thanks!

**Comment by xuchunyang** [comment]
@llcc I'm glad to know you had find solution to this issue.

> The sentence example of looking-up word is very useful in some situations. I am not sure if youdao API opens it or not, but if yes, can you implement it?

No, youdao API doesn't provide example sentence.
