### ISSUE TITLE
有发音的接口吗

### ISSUE THREAD

**Issue by LiuYoung628** [xuchunyang/youdao-dictionary.el#11]

**Comment by xuchunyang** [comment]
有，可用 `M-x youdao-dictionary-play-voice-at-point` 和 `M-x youdao-dictionary-play-voice-from-input`。API 地址为（以单词`example`为例）：http://dict.youdao.com/dictvoice?type=2&audio=example ，不清楚其中参数`type`的含义，猜测是英美音。

**Comment by LiuYoung628** [comment]
的确 type=1是英式
        2是美式

**Comment by LiuYoung628** [comment]
的确 type=1是英式
        2是美式

**Comment by bokuno** [comment]
能增加'mpv'播放器吗?

**Comment by caizhichao** [comment]
查询一个单词并打开新的buffer后
按快捷键p播放声音，会提示下面的信息，看不懂是啥
mplayer or mpg123 is need to play word  voice
