### ISSUE TITLE
M-x youdao-dictionary-from-input 后输入单词，在youdao-dictionary buffer里是VI mode，如何修改其为Emacs mode

### ISSUE THREAD

**Issue by kirchhoff** [xuchunyang/youdao-dictionary.el#13]
如题，请问如何修改呢，我默认使用的是evil的，但是不清楚如何修改查词后默认的编辑模式，我每次都得切换到Emacs mode，然后按q退出那个youdao-dictionary查词结果buffer
![2016-10-17-180813_737x262_scrot](https://cloud.githubusercontent.com/assets/2253887/19433845/fdbd3620-9494-11e6-91af-5cd25d905329.png)

**Comment by xuchunyang** [comment]
我没用过 evil，所以不明白你的的问题。目前 *Youdao Dictionary* 使用 org-mode 显示的，用一个单独的 major-mode 或许有助于问题的解决。

**Comment by kirchhoff** [comment]
恐怕是的，那样或许可以指明evil在youdao-mode下为emacs编辑模式。

**Comment by xuchunyang** [comment]
我已经改成了 youdao-dictionary-mode（继承自 org-mode），youdao-dictionary-mode-map、youdao-dicionary-mode-hook 之类的可以用。

**Comment by kirchhoff** [comment]
谢谢！可以使用！
