### ISSUE TITLE
彈窗框體下方的字體大小和行高與別的區域不一樣

### ISSUE THREAD

**Issue by halfcrazy** [xuchunyang/youdao-dictionary.el#14]
這裏可以設定嗎

**Comment by xuchunyang** [comment]
我这边也有同样的问题（说不定比你的还严重）：

![screenshot from 2016-12-24 18-37-19](https://cloud.githubusercontent.com/assets/4550353/21466457/1ed9d310-ca08-11e6-85ff-865b59eb7771.png)

应该需要在 GUI Emacs 中把中文字体的高度设成与英文字体的相同，宽度也最好设成英文字体的两倍。究竟怎么设置，我不了解，估计网上应该有介绍。终端默认就是这样，得到的效果完全正常：

![screenshot from 2016-12-24 18-40-47](https://cloud.githubusercontent.com/assets/4550353/21466487/deb0200e-ca08-11e6-9274-f50cd7ac691a.png)

**Comment by xuchunyang** [comment]
需要把中文字体的宽度设置为英文的两倍。以下是我目前的设置

```elisp
;; 等宽: Source Code Pro 13 + STkaiti 16
(setq face-font-rescale-alist `(("STkaiti" . ,(/ 16.0 13))))

(set-face-attribute 'default nil :font "Source Code Pro-13")

(set-fontset-font t 'han      (font-spec :family "STkaiti"))
(set-fontset-font t 'cjk-misc (font-spec :family "STkaiti"))
```

![screen shot 2017-02-25 at 12 31 16 pm](https://cloud.githubusercontent.com/assets/4550353/23328178/55f47d9e-fb56-11e6-8d45-3a58eb5762c6.png)
