### ISSUE TITLE
feature request: 用pos-tip来显示结果

### ISSUE THREAD

**Issue by et2010** [xuchunyang/youdao-dictionary.el#16]
非常感谢这么好用的软件！希望能够增加用 pos-tip 来显示查词结果的选项，用popup显示的结果有时会和buffer内容混在一起，很乱，就像这样：

![default](https://cloud.githubusercontent.com/assets/11584902/23336807/58986136-fc15-11e6-915f-8f069b18acb9.png)

**Comment by et2010** [comment]
我试了一下，tootip并没有显示，我用的spacemacs，奇怪啊。

**Comment by xuchunyang** [comment]
你有在用图形界面的 Emacs 吗？因为 Tooltips 是用一个独立的图像界面的窗口来显示的，终端下没效（应该会改用 Echo Area 显示）

**Comment by et2010** [comment]
是图形界面，而且emacs 自带的tooltip.el都能正常显示

**Comment by et2010** [comment]
安装了clippy测试pos-tip是否正常，结果是能够正常显示：
![default](https://cloud.githubusercontent.com/assets/11584902/23337462/90af9fbc-fc29-11e6-8eb3-31290a15e85e.png)

**Comment by xuchunyang** [comment]
你的意思是说 `tooltip-show` 能显示，但 `pos-tip-show` 不能？

```elisp
(tooltip-show "hi")

(require 'pos-tip)
(pos-tip-show "hi")
```

我这里 `pos-tip` 能显示，但是有时候位置会不对。

**Comment by et2010** [comment]
我设定为使用 emacs 图形界面：
```elisp
(setq x-gtk-use-system-tooltips nil)
```
又试了一遍，还是不行。minibuffer显示在尝试连接 youdao，但结果出不来：
![default](https://cloud.githubusercontent.com/assets/11584902/23337493/afbba42c-fc2a-11e6-84b2-a1fbdc82b0ee.png)

**Comment by xuchunyang** [comment]
你可以先试一下以下的是否都正常工作：

```elisp
(tooltip-show "hi")
(pos-tip-show "hi")
```

**Comment by et2010** [comment]
> 你的意思是说 tooltip-show 能显示，但 pos-tip-show 不能？

pos-tip 应该可以用的，clippy用的就是pos-tip，但是直接pos-tip-show显示不了。

**Comment by xuchunyang** [comment]
我不清楚怎么回事，假如你哪里 `(pos-tip-show "foo bar")` 不能正常工作的话，你可能需要向 pos-tip 的作者需求帮助。

**Comment by et2010** [comment]
这就尴尬了，我进入到只加载了 pos-tip 的stock emacs下，可以显示pos-tip了。问题是怎样debug我现在用的emacs配置:sweat:

**Comment by xuchunyang** [comment]
假如你熟悉自己的配置的话，可以把有可能跟 Tooltips 相关的设置逐句注释掉，看看是否变正常了。假如不熟悉的话，可以尝试用二分法（每次注释掉怀疑有问题的配置的一半）找出引起问题的配置。测试的时候，不必重启当前在用的 Emacs，可以直接新开一个。

**Comment by et2010** [comment]
好的，多谢提醒，我用的spacemacs，我先把那些自己写的那些private layer禁用了试试

**Comment by xuchunyang** [comment]
也可以考虑向 Spacemacs 方面寻求帮助

**Comment by et2010** [comment]
嗯，好的，我先看看问题是不是出在我这边。之前提交过几次issue，结果都是我自己的问题，很尴尬 😀

**Comment by et2010** [comment]
我发现 clippy 的函数可以用：
```elisp
(defun clippy-pos-tip-show (string)
  "Show STRING using pos-tip-show."
  (pos-tip-show string nil nil nil 0)
  (unwind-protect
      (push (read-event) unread-command-events)
    (pos-tip-hide)))
```

```elisp
(clippy-pos-tip-show "hello, world!")
```
可以正常显示，问题出在哪呢？

**Comment by et2010** [comment]
换成这个函数就好了，这样org-mode也能够正常显示有道词典了，爽！
![default](https://cloud.githubusercontent.com/assets/11584902/23337679/cfb00858-fc30-11e6-9916-a2e15ae1c49f.png)

**Comment by et2010** [comment]
能不能把这个函数也包含在您的commit中，好像这个wrapper更好用些

**Comment by et2010** [comment]
或者由我发起PR？

**Comment by xuchunyang** [comment]
> 或者由我发起PR？

当然更好了

**Comment by et2010** [comment]
popup方式还保留吗？

**Comment by xuchunyang** [comment]
保留，你写一个新的函数（比如：`youdao-dictionary-search-at-point-tooltip`）

**Comment by et2010** [comment]
OK

**Comment by et2010** [comment]
给需要的朋友：
如果想在除了org-mode之外的地方使用popup，可以用下面的wrapper：
```elisp
(defun et/youdao-search-at-point ()
  (interactive)
  (if (string= major-mode "org-mode")
      (youdao-dictionary-search-at-point-tooltip)
    (youdao-dictionary-search-at-point+)))
```
