### ISSUE TITLE
json-read: JSON readtable error

### ISSUE THREAD

**Issue by crazyatnet** [xuchunyang/youdao-dictionary.el#21]
Contacting host: fanyi.youdao.com:80
json-read: JSON readtable error

**Comment by xuchunyang** [comment]
Oh, same here. The API used in the package has been temporarily disabled by Youdao.

http://fanyi.youdao.com/openapi.do?keyfrom=YouDaoCV&key=659600698&type=data&doctype=json&version=1.1&q=hello

**Comment by xuchunyang** [comment]
It worked just now.
