### ISSUE TITLE
新有道API接口

### ISSUE THREAD

**Issue by seagle0128** [xuchunyang/youdao-dictionary.el#24]
有道宣布将废除老的API，新的API需要重新注册应用 （http://ai.youdao.com/）。
请参考http://ai.youdao.com/doc.s 升级下吧，很喜欢这个package。谢谢！

**Comment by et2010** [comment]
貌似已经不能用了

**Comment by nicehiro** [comment]
https://github.com/xuchunyang/youdao-dictionary.el/pull/26
可以试下这个。

**Comment by lujun9972** [comment]
#26 的api也不是最新的了。
#36 是根据最新的v3版修改的

**Comment by xuchunyang** [comment]
Fixed in #36.
