### ISSUE TITLE
How to set the duration and font size of youdao-dictionary-search-at-point-tooltip

### ISSUE THREAD

**Issue by LuhengStat** [xuchunyang/youdao-dictionary.el#25]
Hi, I think the youdao-dictionary-search-at-point-tooltip is interesting. 
Could you please help about how to set the duration time of this fun. I think its 
a little short and the font size is small. 

Best.

**Comment by xuchunyang** [comment]
I don't know, `youdao-dictionary-search-at-point-tooltip` was implemented by @et2010. However, I think you should be able to achieve what you want if you take a look at `pos-tip.el`, especially the function `pos-tip-show`. To get search result from youdao, use

```elisp
(youdao-dictionary--format-result "hello")
     => "hello [həˈləʊ]

* Basic Explains
- n. 表示问候， 惊奇或唤起注意时的用语
- int. 喂；哈罗
- n. (Hello)人名；(法)埃洛

* Web References
- Hello :: 你好; 您好; hello
- Hello Kitty :: 凯蒂猫; 昵称; 匿称
- Hello Bebe :: 哈乐哈乐; 乐扣乐扣
"
```

**Comment by LuhengStat** [comment]
Thanks. That did solved the problem. I must revised these part by hand, actually I am trying to find a way to  adjust it by customization. 

Best.
