### ISSUE TITLE
youdao-dictionary-search-from-input 每次打开新buffer

### ISSUE THREAD

**Issue by oaksharks** [xuchunyang/youdao-dictionary.el#27]
该函数每次都产生一个新buffer, 当查询多次时会覆盖无辜的window。
多次查询时候应该检查是否已经存在查询结果的buffer， 如果已经存在，就把查询的结果覆盖到此buffer上。

**Comment by whatacold** [comment]
我觉得在当前的查询结果 buffer 增加一个快捷键，比如 `q` 就可以接着输入查询，结果覆盖显示在当前 buffer （没记错的话， `sdcv` 就是这样的）。

我觉得这样在连续查词的情况下，更易用一些。

**Comment by xuchunyang** [comment]
@whatacold 你可以自己绑定按键到 `youdao-dictionary-mode-map`。

**Comment by whatacold** [comment]
ok，原来还可以这么设置。

    (define-key youdao-dictionary-mode-map
      (kbd "s") #'youdao-dictionary-search-from-input)

就是 buffer 还会有多个，不过按 `q` 能快速退出，也还好

**Comment by xuchunyang** [comment]
> 就是 buffer 还会有多个

过几个小时更新下 `youdao-dictionary`，我已经尝试用 beb7faf 解决了。
