### ISSUE TITLE
feature request:能否支持用posframe来显示结果

### ISSUE THREAD

**Issue by darcylee** [xuchunyang/youdao-dictionary.el#30]
能否支持posframe显示呢？
目前支持的问题：
popup，在有些时候会出现显示不对齐(如中英文配置不对齐、开启fill-column-indicator模式后）
tooltip 只能在UI下使用，terminal模式无法使用

emacs 26.x 可以使用posframe， 在UI和terminal模式都可以比较好的支持

**Comment by xuchunyang** [comment]
指的是 [posframe](https://github.com/tumashu/posframe) 吧，估计可以的啦，但我不了解 posframe / child frame，有需求的话，最好你自己先试试。

**Comment by darcylee** [comment]
> 指的是 [posframe](https://github.com/tumashu/posframe) 吧，估计可以的啦，但我不了解 posframe / child frame，有需求的话，最好你自己先试试。

嗯， 是，拼写错误
