### ISSUE TITLE
请问兼容 Mac OS/Windows 吗？

### ISSUE THREAD

**Issue by yibie** [xuchunyang/youdao-dictionary.el#48]
如题。

因为我阅读了 README，没有提示系统兼容性的问题。然后我阅读了一下代码，发现有可能需要用到某些系统特性，不知道是否兼容 Mac OS/Windows 呢？

**Comment by xuchunyang** [comment]
兼容 Mac 和 Windows 的，只依赖 Emacs 自身，Emacs 能跑这个包就能用。

**Comment by yibie** [comment]
感谢，那太棒了！
