### ISSUE TITLE
Can't translate long sentences?

### ISSUE THREAD

**Issue by andyque** [xuchunyang/youdao-dictionary.el#5]
Eg. The sentence  "please refer to this document"  won't be translated in the popwin.

Here is the screenshot.

![qq20150421-1 2x](https://cloud.githubusercontent.com/assets/785541/7245070/abb08510-e817-11e4-94de-45510003203e.png)

**Comment by xuchunyang** [comment]
This issue should be fixed now.  Thank you for reporting it.
