### ISSUE TITLE
不能访问服务器了

### ISSUE THREAD

**Issue by yinxiuqu** [xuchunyang/youdao-dictionary.el#51]
Contacting host: fanyi.youdao.com:80
youdao-dictionary--parse-response: Problem connecting to the server

**Comment by daotoyi** [comment]
> Contacting host: fanyi.youdao.com:80 youdao-dictionary--parse-response: Problem connecting to the server

应该是有道云的openapi停止访问了（http://fanyi.youdao.com/openapi）

**Comment by urugang** [comment]
需要设置api key
```
(use-package youdao-dictionary
  :ensure
  :config
  (setq youdao-dictionary-app-key "7a8b22fe546e4c92")
  (setq youdao-dictionary-secret-key "iqOExxkEm7Yl0z11CzA5sBd3zwMI1Mg0"))
```

**Comment by xuchunyang** [comment]
我这儿还行，如果访问失败，申请 API 是靠谱的方法
