### ISSUE TITLE
Contacting host: fanyi.youdao.com:80 ERROR

### ISSUE THREAD

**Issue by OrionRandD** [xuchunyang/youdao-dictionary.el#53]
I am having problems to contact to the dictionary server

Contacting host: fanyi.youdao.com:80
prog1: JSON readtable error: 60
Contacting host: fanyi.youdao.com:80
progn: Problem connecting to the server
Contacting host: fanyi.youdao.com:80
progn: Problem connecting to the server
Contacting host: fanyi.youdao.com:80
progn: Problem connecting to the server
Contacting host: melpa.org:80

Contacting host: fanyi.youdao.com:80
youdao-dictionary--parse-response: JSON readtable error: 60
Contacting host: fanyi.youdao.com:80
youdao-dictionary--parse-response: JSON readtable error: 60
Contacting host: fanyi.youdao.com:80
error in process filter: youdao-dictionary--parse-response: JSON readtable error: 60
error in process filter: JSON readtable error: 60

My Emacs version:
GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.16.0) of 2023-08-30, modified by Debian

**Comment by xuchunyang** [comment]
默认免费的 API 已经无法使用，已经被有道停止了。

如果还需要需要这个包，自行申请 API，再设置相关变量（API Secret/Key）。

还可以尝试其他的包，比如 https://github.com/cute-jumper/bing-dict.el 提供了免费的 Bing 翻译，无需 API。

**Comment by xuchunyang** [comment]
I have disabled the free API in the code, if you use the package without your own API, you'll be warned, so you can know what's going on. The README.md is also updated to reflect the change.
