### ISSUE TITLE
第二次查找的时候报错

### ISSUE THREAD

**Issue by taxusyew** [xuchunyang/youdao-dictionary.el#9]
Contacting host: fanyi.youdao.com:80
byte-code: Invalid date: 06-Sep-2045 07:57:42.00 GMT
error in process sentinel: byte-code: Invalid date: 06-Sep-2045 07:57:42.00 GMT
error in process sentinel: Invalid date: 06-Sep-2045 07:57:42.00 GMT
command-execute: Buffer is read-only: #<buffer *Messages*>

**Comment by banyudu** [comment]
我也遇到这个问题，请问是如何解决的？
